package com.mapbox.maps.plugin

const val MAPBOX_CAMERA_PLUGIN = "MAPBOX_CAMERA"
const val MAPBOX_GESTURES_PLUGIN = "MAPBOX_GESTURES"
const val MAPBOX_COMPASS_PLUGIN = "MAPBOX_COMPASS"
const val MAPBOX_LOGO_PLUGIN = "MAPBOX_LOGO"
const val MAPBOX_ATTRIBUTION_PLUGIN = "MAPBOX_ATTRIBUTION"
const val MAPBOX_LOCATION_COMPONENT_PLUGIN = "MAPBOX_LOCATION_COMPONENT"
const val MAPBOX_SCALEBAR_PLUGIN = "MAPBOX_SCALEBAR"
const val MAPBOX_ANNOTATION_PLUGIN = "MAPBOX_ANNOTATION"
const val MAPBOX_LIFECYCLE_PLUGIN = "MAPBOX_LIFECYCLE"
const val MAPBOX_MAP_OVERLAY_PLUGIN = "MAPBOX_MAP_OVERLAY"