[versions]

# Mapbox NDK Gradle Plugin will read these versions to figure out what NDK versions are supported in
# this codebase.
defaultNdkMajor = "21"
ndkMajor21 = "21.4.7075529"
ndkMajor27 = "27.0.12077973"